services:
  backlog-db:
    container_name: postgres-backlog
    image: postgres:15-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "backlogdb" ]
    environment:
      POSTGRES_DB: backlogdb
      POSTGRES_USER: frieren
      POSTGRES_PASSWORD: slayer
    ports:
      - 5432:5432

  keycloak-db:
    container_name: postgres-kc
    image: postgres:15-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "keycloak" ]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: frieren
      POSTGRES_PASSWORD: slayer
    volumes:
        - ./keycloak_db:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: frieren
      KC_DB_PASSWORD: slayer
      KC_DB_URL: "jdbc:postgresql://postgres-kc:5432/keycloak"
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    depends_on:
      - keycloak-db
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro

volumes:
  keycloak_db:
    driver: local
